spring.application.name=product-api
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.root=INFO
logging.level.com.meli.productapi=DEBUG

# Jackson
spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false
